//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRM_V3.assets
{
    using System;
    using System.Collections.Generic;
    
    public partial class CostCenterSetup
    {
        public string CompanyCode { get; set; }
        public string CSCode { get; set; }
        public Nullable<System.DateTime> CSDate { get; set; }
        public string CSName { get; set; }
        public string Remarks { get; set; }
        public string CSTypeCode { get; set; }
        public Nullable<System.DateTime> EffectiveFromDate { get; set; }
        public Nullable<System.DateTime> EffectiveToDate { get; set; }
        public string IsActive { get; set; }
        public string UpdUser { get; set; }
        public Nullable<System.DateTime> UpdDate { get; set; }
        public Nullable<System.DateTime> UpdTime { get; set; }
        public string UpdTerm { get; set; }
        public string IsDefault { get; set; }
    }
}
