//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRM_V3.assets
{
    using System;
    using System.Collections.Generic;
    
    public partial class DailyExpenseMaster
    {
        public string DealerCode { get; set; }
        public string ExpInvNo { get; set; }
        public Nullable<System.DateTime> ExpInvDate { get; set; }
        public string Remarks { get; set; }
        public string CBCode { get; set; }
        public string PayModeCode { get; set; }
        public string InsNo { get; set; }
        public Nullable<System.DateTime> InsDate { get; set; }
        public Nullable<double> InsAmount { get; set; }
        public string BankCode { get; set; }
        public string Branch { get; set; }
        public Nullable<double> ExpTotalInvAmount { get; set; }
        public string DelFlag { get; set; }
        public string PostFlag { get; set; }
        public string VoucherNo { get; set; }
        public string VoucherFlag { get; set; }
        public string UpdUser { get; set; }
        public Nullable<System.DateTime> UpdDate { get; set; }
        public Nullable<System.DateTime> UpdTime { get; set; }
        public string UpdTerm { get; set; }
        public string CSCode { get; set; }
    }
}
