//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRM_V3.assets
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExpenseHead
    {
        public string DealerCode { get; set; }
        public string ECode { get; set; }
        public string EDesc { get; set; }
        public string AccountCode { get; set; }
        public string UpdUser { get; set; }
        public Nullable<System.DateTime> UpdDate { get; set; }
        public Nullable<System.DateTime> UpdTime { get; set; }
        public string UpdTerm { get; set; }
    }
}
