//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRM_V3.assets
{
    using System;
    using System.Collections.Generic;
    
    public partial class PaymentMode
    {
        public string DealerCode { get; set; }
        public string PayModeCode { get; set; }
        public string PayModeDesc { get; set; }
        public string UpdUser { get; set; }
        public System.DateTime UpdDate { get; set; }
        public System.DateTime UpdTime { get; set; }
        public string UpdTerm { get; set; }
        public string Version { get; set; }
        public string PayModeCodeOEM { get; set; }
    }
}
