//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRM_V3.assets
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bank
    {
        public string DealerCode { get; set; }
        public string BankCode { get; set; }
        public string BankDesc { get; set; }
        public string UpdUser { get; set; }
        public Nullable<System.DateTime> UpdDate { get; set; }
        public Nullable<System.DateTime> UpdTime { get; set; }
        public string UpdTerm { get; set; }
        public string BankStatus { get; set; }
        public Nullable<bool> OEMFinance { get; set; }
    }
}
