//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRM_V3.assets
{
    using System;
    using System.Collections.Generic;
    
    public partial class CashBankSetup
    {
        public string CompanyCode { get; set; }
        public string CBCode { get; set; }
        public string CBDesc { get; set; }
        public string ACType { get; set; }
        public string FAMSACNo { get; set; }
        public string AccountCode { get; set; }
        public Nullable<double> OpeningBalance { get; set; }
        public string UpdUser { get; set; }
        public Nullable<System.DateTime> UpdDate { get; set; }
        public Nullable<System.DateTime> UpdTime { get; set; }
        public string UpdTerm { get; set; }
        public string Delflag { get; set; }
    }
}
