//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRM_V3.assets
{
    using System;
    using System.Collections.Generic;
    
    public partial class DailyExpenseDetail
    {
        public string DealerCode { get; set; }
        public string ExpInvNo { get; set; }
        public string ExpFor { get; set; }
        public string ExpPayTo { get; set; }
        public string ExpRemarks { get; set; }
        public Nullable<double> Amount { get; set; }
        public string AccountCode { get; set; }
    }
}
