//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRM_V3.assets
{
    using System;
    using System.Collections.Generic;
    
    public partial class DealerEmp
    {
        public string DealerCode { get; set; }
        public string EmpCode { get; set; }
        public string EmpName { get; set; }
        public Nullable<System.DateTime> JoiningDate { get; set; }
        public string ContactNo { get; set; }
        public Nullable<System.DateTime> DOB { get; set; }
        public byte Experience { get; set; }
        public Nullable<System.DateTime> LeavingDate { get; set; }
        public string DesigCode { get; set; }
        public string DeptCode { get; set; }
        public string Remarks { get; set; }
        public string PrimaryTechCode { get; set; }
        public string UserName { get; set; }
        public string Password { get; set; }
        public string Role { get; set; }
        public string Active { get; set; }
        public string SecurityUserID { get; set; }
        public string CNIC { get; set; }
        public string EmpID { get; set; }
        public string Picture { get; set; }
        public string Email { get; set; }
    }
}
