//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRM_V3.assets
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class sngonclo_BMSEntities : DbContext
    {
        public sngonclo_BMSEntities()
            : base("name=sngonclo_BMSEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Bank> Banks { get; set; }
        public virtual DbSet<CashBankSetup> CashBankSetups { get; set; }
        public virtual DbSet<DailyExpenseMaster> DailyExpenseMasters { get; set; }
        public virtual DbSet<DealerEmp> DealerEmps { get; set; }
        public virtual DbSet<ExpenseHead> ExpenseHeads { get; set; }
        public virtual DbSet<PaymentMode> PaymentModes { get; set; }
        public virtual DbSet<ReceiptHead> ReceiptHeads { get; set; }
        public virtual DbSet<CostCenterSetup> CostCenterSetups { get; set; }
        public virtual DbSet<DailyExpenseDetail> DailyExpenseDetails { get; set; }
        public virtual DbSet<City> Cities { get; set; }
        public virtual DbSet<PaymentReceiptMaster> PaymentReceiptMaster { get; set; }
        public virtual DbSet<PaymentReceiptDetail> PaymentReceiptDetail { get; set; }
        public virtual DbSet<PaymentReceiptTaxDetail> PaymentReceiptTaxDetail { get; set; }
        public virtual DbSet<VehicleDeliveryDetail> VehicleDeliveryDetail { get; set; }
        public virtual DbSet<VehicleDeliveryMaster> VehicleDeliveryMaster { get; set; }
        public virtual DbSet<VehicleStock> VehicleStock { get; set; }
        public virtual DbSet<Vendor> Vendor { get; set; }
    
        public virtual ObjectResult<string> sp_ExpInvNo_DailyExpenseMaster()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("sp_ExpInvNo_DailyExpenseMaster");
        }
    }
}
