//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRM_V3.assets
{
    using System;
    using System.Collections.Generic;
    
    public partial class PaymentReceiptMaster
    {
        public string DealerCode { get; set; }
        public string ReceiptNo { get; set; }
        public System.DateTime ReceiptDate { get; set; }
        public string InvoiceType { get; set; }
        public string CusCode { get; set; }
        public string InsCompCode { get; set; }
        public string BranchCode { get; set; }
        public string InsCusFlag { get; set; }
        public string Remarks { get; set; }
        public string PayModeCode { get; set; }
        public string InsNo { get; set; }
        public Nullable<System.DateTime> InsDate { get; set; }
        public double AmountPaid { get; set; }
        public string BankCode { get; set; }
        public string Branch { get; set; }
        public Nullable<double> AdvanceAmount { get; set; }
        public double InvTotal { get; set; }
        public double OutSTTotal { get; set; }
        public double InvAdjTotal { get; set; }
        public string DelFlag { get; set; }
        public string UpdUser { get; set; }
        public System.DateTime UpdDate { get; set; }
        public System.DateTime UpdTime { get; set; }
        public string UpdTerm { get; set; }
        public string VoucherNo { get; set; }
        public string VoucherFlag { get; set; }
        public Nullable<decimal> AdvancePaid { get; set; }
        public string TransType { get; set; }
        public string IsAdjustAdvance { get; set; }
        public string AdvanceReceiptNo { get; set; }
        public Nullable<double> AdvanceAdjustedAmount { get; set; }
        public Nullable<double> AdvanceBalanceAmount { get; set; }
        public string DocumentNo { get; set; }
        public string RefundPayment { get; set; }
        public Nullable<double> RefundAmount { get; set; }
    }
}
