//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRM_V3.assets
{
    using System;
    using System.Collections.Generic;
    
    public partial class PaymentReceiptDetail
    {
        public string DealerCode { get; set; }
        public string ReceiptNo { get; set; }
        public string InvoiceType { get; set; }
        public string InvoiceNo { get; set; }
        public System.DateTime InvoiceDate { get; set; }
        public double InvAmount { get; set; }
        public double OutStAmount { get; set; }
        public double AdjAmount { get; set; }
    }
}
