//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRM_V3.assets
{
    using System;
    using System.Collections.Generic;
    
    public partial class PaymentReceiptTaxDetail
    {
        public string DealerCode { get; set; }
        public string ReceiptNo { get; set; }
        public string ReceiptHead { get; set; }
        public string AccountCode { get; set; }
        public Nullable<double> Amount { get; set; }
        public string TaxID { get; set; }
        public Nullable<decimal> TaxPerc { get; set; }
    }
}
