//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRM_V3.assets
{
    using System;
    using System.Collections.Generic;
    
    public partial class VehicleDeliveryDetail
    {
        public string DealerCode { get; set; }
        public string DeliveryNo { get; set; }
        public string BrandCode { get; set; }
        public string ProdCode { get; set; }
        public string VersionCode { get; set; }
        public string EngineNo { get; set; }
        public string ChasisNo { get; set; }
        public Nullable<double> ExFactPrice { get; set; }
        public string ColorCode { get; set; }
        public string ProdRecNo { get; set; }
        public string LocCode { get; set; }
        public string EnquiryNo { get; set; }
        public string StockType { get; set; }
        public string BookingNo { get; set; }
        public string DocumentNo { get; set; }
    
        public virtual VehicleDeliveryMaster VehicleDeliveryMaster { get; set; }
    }
}
