//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRM_V3.assets
{
    using System;
    using System.Collections.Generic;
    
    public partial class VehicleDeliveryMaster
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public VehicleDeliveryMaster()
        {
            this.VehicleDeliveryDetail = new HashSet<VehicleDeliveryDetail>();
        }
    
        public string DealerCode { get; set; }
        public string DeliveryNo { get; set; }
        public System.DateTime DeliveryDate { get; set; }
        public string BookingNo { get; set; }
        public string BookRefNo { get; set; }
        public string CusCode { get; set; }
        public string DelFlag { get; set; }
        public string UpdUser { get; set; }
        public System.DateTime UpdDate { get; set; }
        public System.DateTime UpdTime { get; set; }
        public string UpdTerm { get; set; }
        public string Reciever { get; set; }
        public Nullable<System.DateTime> DeliveryTime { get; set; }
        public string Type { get; set; }
        public string ReceiverCode { get; set; }
        public string IsSalePerson { get; set; }
        public string DONotCode { get; set; }
        public string Remarks { get; set; }
        public string PSFFlag { get; set; }
        public Nullable<System.DateTime> PSFDate { get; set; }
        public string PSFDFlag { get; set; }
        public Nullable<System.DateTime> PSFDDate { get; set; }
        public string TransferStatus { get; set; }
        public string EnquiryNo { get; set; }
        public string EmpCode { get; set; }
        public string DOType { get; set; }
        public string Segment { get; set; }
        public string Usage { get; set; }
        public string VehTypeCode { get; set; }
        public string VehRecCode { get; set; }
        public string CusContNo { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VehicleDeliveryDetail> VehicleDeliveryDetail { get; set; }
    }
}
