//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRM_V3.assets
{
    using System;
    using System.Collections.Generic;
    
    public partial class VehicleStock
    {
        public string DealerCode { get; set; }
        public string LocCode { get; set; }
        public string BrandCode { get; set; }
        public string ProdCode { get; set; }
        public string VersionCode { get; set; }
        public string ColorCode { get; set; }
        public string EngineNo { get; set; }
        public string ChasisNo { get; set; }
        public string RegNo { get; set; }
        public string Remarks { get; set; }
        public Nullable<double> Amount { get; set; }
        public string ModelYear { get; set; }
        public string DeliveryFlag { get; set; }
        public string InStockFlag { get; set; }
        public string CusCode { get; set; }
        public string InvoiceNo { get; set; }
        public Nullable<System.DateTime> InvoiceDate { get; set; }
        public string BookingNo { get; set; }
        public string BookingRefNo { get; set; }
        public Nullable<System.DateTime> InDate { get; set; }
        public Nullable<System.DateTime> OutDate { get; set; }
        public Nullable<System.DateTime> BookingRefDate { get; set; }
        public string ColorDesc { get; set; }
        public string DisplayName { get; set; }
        public string CusDesc { get; set; }
        public Nullable<System.DateTime> DeliveryDate { get; set; }
        public Nullable<System.DateTime> RegDate { get; set; }
        public string InsCompCode { get; set; }
        public string InsPolicyNo { get; set; }
        public string LossNo { get; set; }
        public Nullable<System.DateTime> InsDate { get; set; }
        public Nullable<System.DateTime> BookRecDate { get; set; }
        public Nullable<System.DateTime> BookIssueDate { get; set; }
        public string Type { get; set; }
        public Nullable<bool> Blocked { get; set; }
        public string BlockedBy { get; set; }
        public Nullable<System.DateTime> BlockedDate { get; set; }
        public string SaleAble { get; set; }
        public string EnquiryNo { get; set; }
        public string RecNo { get; set; }
        public string OrderNo { get; set; }
        public Nullable<System.DateTime> OrderDate { get; set; }
        public string HoldFlag { get; set; }
        public string HoldBy { get; set; }
        public string HoldTill { get; set; }
        public Nullable<double> HoldAmount { get; set; }
        public Nullable<System.DateTime> HoldDate { get; set; }
        public string FreightLoc { get; set; }
        public Nullable<double> FreightCharge { get; set; }
        public string FCode { get; set; }
        public Nullable<double> StockValue { get; set; }
        public Nullable<double> FeaturePrice { get; set; }
        public Nullable<System.DateTime> TransportDelivery { get; set; }
        public string LedgerType { get; set; }
        public string HoldAt { get; set; }
    }
}
