//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRM_V3.assets
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vendor
    {
        public string DealerCode { get; set; }
        public string VendorCode { get; set; }
        public string VendorDesc { get; set; }
        public string Add1 { get; set; }
        public string Add2 { get; set; }
        public string Add3 { get; set; }
        public string ContPerson { get; set; }
        public string Phone1 { get; set; }
        public string Phone2 { get; set; }
        public string Fax { get; set; }
        public string Email { get; set; }
        public string URL { get; set; }
        public string GSTno { get; set; }
        public string NTN { get; set; }
        public string PaymentTerm { get; set; }
        public string AccountCode { get; set; }
        public Nullable<double> AdvanceGiven { get; set; }
        public string UpdUser { get; set; }
        public System.DateTime UpdDate { get; set; }
        public System.DateTime UpdTime { get; set; }
        public string UpdTerm { get; set; }
        public Nullable<double> CreditLimit { get; set; }
        public string Title { get; set; }
        public string VendorRecievable { get; set; }
        public string VendorPayable { get; set; }
        public string DeafultVendor { get; set; }
    }
}
